### ISSUE TITLE
`begin` should not introduce new scope

### ISSUE THREAD

**Issue by dram** [etaoins/llambda#56]
Llambda failed to compile following two code snippets and raise `io.llambda.compiler.UnboundVariableException`.

According to scheme report, I think `begin` should not introduce new scope.

toplevel: 

    (begin
      (define foo "foo"))
    
    (write-string foo)

inside `define`:

    (define (bar)
      (begin
        (define s "bar"))
      s)

**Comment by etaoins** [comment]
In R7RS Section 4.2.3 there seems to be two distinct forms of ``(begin)``: body/top-level and expression. Your first example is of the top-level form because it appears in a top-level context and its result is unused. The second example is an expression form because it's being used as an expression for initialising ``s``

I think you're completely correct that we're not handling the body form correctly and that's a bug. However, I think the expression form should introduce a new scope based on the example ``(begin)`` macro in Section 7.3:

```scheme
(define-syntax begin
  (syntax-rules ()
    ((begin exp ...)
      ((lambda () exp ...)))))
```

This will clearly create a new scope due to the enclosing ``(lambda)``.

Does this make sense? I'll look at fixing the top-level form if you don't have any objections.

**Comment by dram** [comment]
Maybe you misread something? In second example, `begin` wrap an internal definition, its result is unused, so I think this usage of `begin` still belongs to `body/top-level` form.

**Comment by etaoins** [comment]
Sorry you're right. I thought the second example was a variable delcaration because I missed the lambda shorthand form
